'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WcfTrylogycWebsite
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BaseRequest", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.ServiceRequests"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfTrylogycWebsite.FacturaPdfRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfTrylogycWebsite.LoginRequest))>  _
    Partial Public Class BaseRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TokenField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Token() As String
            Get
                Return Me.TokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TokenField, value) <> true) Then
                    Me.TokenField = value
                    Me.RaisePropertyChanged("Token")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FacturaPdfRequest", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.ServiceRequests"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FacturaPdfRequest
        Inherits WcfTrylogycWebsite.BaseRequest
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssociateIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConnectionIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RetrieveFromFTPField As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssociateId() As Integer
            Get
                Return Me.AssociateIdField
            End Get
            Set
                If (Me.AssociateIdField.Equals(value) <> true) Then
                    Me.AssociateIdField = value
                    Me.RaisePropertyChanged("AssociateId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ConnectionId() As Integer
            Get
                Return Me.ConnectionIdField
            End Get
            Set
                If (Me.ConnectionIdField.Equals(value) <> true) Then
                    Me.ConnectionIdField = value
                    Me.RaisePropertyChanged("ConnectionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceNumber() As String
            Get
                Return Me.InvoiceNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceNumberField, value) <> true) Then
                    Me.InvoiceNumberField = value
                    Me.RaisePropertyChanged("InvoiceNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RetrieveFromFTP() As Boolean
            Get
                Return Me.RetrieveFromFTPField
            End Get
            Set
                If (Me.RetrieveFromFTPField.Equals(value) <> true) Then
                    Me.RetrieveFromFTPField = value
                    Me.RaisePropertyChanged("RetrieveFromFTP")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LoginRequest", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.ServiceRequests"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LoginRequest
        Inherits WcfTrylogycWebsite.BaseRequest
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserNameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserName() As String
            Get
                Return Me.UserNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserNameField, value) <> true) Then
                    Me.UserNameField = value
                    Me.RaisePropertyChanged("UserName")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BaseResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.ServiceResponses"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfTrylogycWebsite.FacturaPdfResponse)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfTrylogycWebsite.RegisterResponse)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfTrylogycWebsite.LoginResponse))>  _
    Partial Public Class BaseResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusCodeField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusCode() As Integer
            Get
                Return Me.StatusCodeField
            End Get
            Set
                If (Me.StatusCodeField.Equals(value) <> true) Then
                    Me.StatusCodeField = value
                    Me.RaisePropertyChanged("StatusCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FacturaPdfResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.ServiceResponses"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FacturaPdfResponse
        Inherits WcfTrylogycWebsite.BaseResponse
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoicePdfField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoicePdf() As String
            Get
                Return Me.InvoicePdfField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoicePdfField, value) <> true) Then
                    Me.InvoicePdfField = value
                    Me.RaisePropertyChanged("InvoicePdf")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RegisterResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.ServiceResponses"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RegisterResponse
        Inherits WcfTrylogycWebsite.BaseResponse
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LoginResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.ServiceResponses"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LoginResponse
        Inherits WcfTrylogycWebsite.BaseResponse
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TokenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserField As WcfTrylogycWebsite.WcfUser
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Token() As String
            Get
                Return Me.TokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TokenField, value) <> true) Then
                    Me.TokenField = value
                    Me.RaisePropertyChanged("Token")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property User() As WcfTrylogycWebsite.WcfUser
            Get
                Return Me.UserField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserField, value) <> true) Then
                    Me.UserField = value
                    Me.RaisePropertyChanged("User")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WcfUser", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WcfUser
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssociatesField() As WcfTrylogycWebsite.WcfAssociate
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssociatesConnectionsField() As WcfTrylogycWebsite.WcfAssociateConnection
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BalancesField() As WcfTrylogycWebsite.WcfBalance
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailInvoiceField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PictureField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RouteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalConnectionsField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Associates() As WcfTrylogycWebsite.WcfAssociate()
            Get
                Return Me.AssociatesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssociatesField, value) <> true) Then
                    Me.AssociatesField = value
                    Me.RaisePropertyChanged("Associates")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssociatesConnections() As WcfTrylogycWebsite.WcfAssociateConnection()
            Get
                Return Me.AssociatesConnectionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssociatesConnectionsField, value) <> true) Then
                    Me.AssociatesConnectionsField = value
                    Me.RaisePropertyChanged("AssociatesConnections")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Balances() As WcfTrylogycWebsite.WcfBalance()
            Get
                Return Me.BalancesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BalancesField, value) <> true) Then
                    Me.BalancesField = value
                    Me.RaisePropertyChanged("Balances")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmailInvoice() As Boolean
            Get
                Return Me.EmailInvoiceField
            End Get
            Set
                If (Me.EmailInvoiceField.Equals(value) <> true) Then
                    Me.EmailInvoiceField = value
                    Me.RaisePropertyChanged("EmailInvoice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Picture() As String
            Get
                Return Me.PictureField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PictureField, value) <> true) Then
                    Me.PictureField = value
                    Me.RaisePropertyChanged("Picture")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Route() As String
            Get
                Return Me.RouteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RouteField, value) <> true) Then
                    Me.RouteField = value
                    Me.RaisePropertyChanged("Route")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalConnections() As Integer
            Get
                Return Me.TotalConnectionsField
            End Get
            Set
                If (Me.TotalConnectionsField.Equals(value) <> true) Then
                    Me.TotalConnectionsField = value
                    Me.RaisePropertyChanged("TotalConnections")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserName() As String
            Get
                Return Me.UserNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserNameField, value) <> true) Then
                    Me.UserNameField = value
                    Me.RaisePropertyChanged("UserName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WcfAssociate", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WcfAssociate
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CGPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConnectionIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As String
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CGP() As String
            Get
                Return Me.CGPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CGPField, value) <> true) Then
                    Me.CGPField = value
                    Me.RaisePropertyChanged("CGP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ConnectionId() As Integer
            Get
                Return Me.ConnectionIdField
            End Get
            Set
                If (Me.ConnectionIdField.Equals(value) <> true) Then
                    Me.ConnectionIdField = value
                    Me.RaisePropertyChanged("ConnectionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Document() As String
            Get
                Return Me.DocumentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentField, value) <> true) Then
                    Me.DocumentField = value
                    Me.RaisePropertyChanged("Document")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WcfAssociateConnection", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WcfAssociateConnection
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssociateIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConnectionIdField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssociateId() As Integer
            Get
                Return Me.AssociateIdField
            End Get
            Set
                If (Me.AssociateIdField.Equals(value) <> true) Then
                    Me.AssociateIdField = value
                    Me.RaisePropertyChanged("AssociateId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ConnectionId() As Integer
            Get
                Return Me.ConnectionIdField
            End Get
            Set
                If (Me.ConnectionIdField.Equals(value) <> true) Then
                    Me.ConnectionIdField = value
                    Me.RaisePropertyChanged("ConnectionId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WcfBalance", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WcfBalance
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssociateIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConnectionIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceAmmountField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceExpirationDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceGroupField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceLetterField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoicePointField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceTrackingNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PaidField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PeriodField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssociateId() As Integer
            Get
                Return Me.AssociateIdField
            End Get
            Set
                If (Me.AssociateIdField.Equals(value) <> true) Then
                    Me.AssociateIdField = value
                    Me.RaisePropertyChanged("AssociateId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ConnectionId() As Integer
            Get
                Return Me.ConnectionIdField
            End Get
            Set
                If (Me.ConnectionIdField.Equals(value) <> true) Then
                    Me.ConnectionIdField = value
                    Me.RaisePropertyChanged("ConnectionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceAmmount() As String
            Get
                Return Me.InvoiceAmmountField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceAmmountField, value) <> true) Then
                    Me.InvoiceAmmountField = value
                    Me.RaisePropertyChanged("InvoiceAmmount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceDate() As String
            Get
                Return Me.InvoiceDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceDateField, value) <> true) Then
                    Me.InvoiceDateField = value
                    Me.RaisePropertyChanged("InvoiceDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceExpirationDate() As String
            Get
                Return Me.InvoiceExpirationDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceExpirationDateField, value) <> true) Then
                    Me.InvoiceExpirationDateField = value
                    Me.RaisePropertyChanged("InvoiceExpirationDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceGroup() As String
            Get
                Return Me.InvoiceGroupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceGroupField, value) <> true) Then
                    Me.InvoiceGroupField = value
                    Me.RaisePropertyChanged("InvoiceGroup")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceLetter() As String
            Get
                Return Me.InvoiceLetterField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceLetterField, value) <> true) Then
                    Me.InvoiceLetterField = value
                    Me.RaisePropertyChanged("InvoiceLetter")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceNumber() As String
            Get
                Return Me.InvoiceNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceNumberField, value) <> true) Then
                    Me.InvoiceNumberField = value
                    Me.RaisePropertyChanged("InvoiceNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoicePoint() As String
            Get
                Return Me.InvoicePointField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoicePointField, value) <> true) Then
                    Me.InvoicePointField = value
                    Me.RaisePropertyChanged("InvoicePoint")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceTrackingNumber() As String
            Get
                Return Me.InvoiceTrackingNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceTrackingNumberField, value) <> true) Then
                    Me.InvoiceTrackingNumberField = value
                    Me.RaisePropertyChanged("InvoiceTrackingNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Paid() As Boolean
            Get
                Return Me.PaidField
            End Get
            Set
                If (Me.PaidField.Equals(value) <> true) Then
                    Me.PaidField = value
                    Me.RaisePropertyChanged("Paid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Period() As String
            Get
                Return Me.PeriodField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PeriodField, value) <> true) Then
                    Me.PeriodField = value
                    Me.RaisePropertyChanged("Period")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RegisterRequest", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfTrylogycWebsite.ServiceRequests"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RegisterRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CGPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailConfirmField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailInvoicesField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CGP() As String
            Get
                Return Me.CGPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CGPField, value) <> true) Then
                    Me.CGPField = value
                    Me.RaisePropertyChanged("CGP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodeField, value) <> true) Then
                    Me.CodeField = value
                    Me.RaisePropertyChanged("Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmailConfirm() As String
            Get
                Return Me.EmailConfirmField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailConfirmField, value) <> true) Then
                    Me.EmailConfirmField = value
                    Me.RaisePropertyChanged("EmailConfirm")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmailInvoices() As Boolean
            Get
                Return Me.EmailInvoicesField
            End Get
            Set
                If (Me.EmailInvoicesField.Equals(value) <> true) Then
                    Me.EmailInvoicesField = value
                    Me.RaisePropertyChanged("EmailInvoices")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WcfTrylogycWebsite.IService")>  _
    Public Interface IService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/Login", ReplyAction:="http://tempuri.org/IService/LoginResponse")>  _
        Function Login(ByVal request As WcfTrylogycWebsite.LoginRequest) As WcfTrylogycWebsite.LoginResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/Login", ReplyAction:="http://tempuri.org/IService/LoginResponse")>  _
        Function LoginAsync(ByVal request As WcfTrylogycWebsite.LoginRequest) As System.Threading.Tasks.Task(Of WcfTrylogycWebsite.LoginResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetInvoicePdf", ReplyAction:="http://tempuri.org/IService/GetInvoicePdfResponse")>  _
        Function GetInvoicePdf(ByVal request As WcfTrylogycWebsite.FacturaPdfRequest) As WcfTrylogycWebsite.FacturaPdfResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/GetInvoicePdf", ReplyAction:="http://tempuri.org/IService/GetInvoicePdfResponse")>  _
        Function GetInvoicePdfAsync(ByVal request As WcfTrylogycWebsite.FacturaPdfRequest) As System.Threading.Tasks.Task(Of WcfTrylogycWebsite.FacturaPdfResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/Register", ReplyAction:="http://tempuri.org/IService/RegisterResponse")>  _
        Function Register(ByVal request As WcfTrylogycWebsite.RegisterRequest) As WcfTrylogycWebsite.RegisterResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/Register", ReplyAction:="http://tempuri.org/IService/RegisterResponse")>  _
        Function RegisterAsync(ByVal request As WcfTrylogycWebsite.RegisterRequest) As System.Threading.Tasks.Task(Of WcfTrylogycWebsite.RegisterResponse)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceChannel
        Inherits WcfTrylogycWebsite.IService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceClient
        Inherits System.ServiceModel.ClientBase(Of WcfTrylogycWebsite.IService)
        Implements WcfTrylogycWebsite.IService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Login(ByVal request As WcfTrylogycWebsite.LoginRequest) As WcfTrylogycWebsite.LoginResponse Implements WcfTrylogycWebsite.IService.Login
            Return MyBase.Channel.Login(request)
        End Function
        
        Public Function LoginAsync(ByVal request As WcfTrylogycWebsite.LoginRequest) As System.Threading.Tasks.Task(Of WcfTrylogycWebsite.LoginResponse) Implements WcfTrylogycWebsite.IService.LoginAsync
            Return MyBase.Channel.LoginAsync(request)
        End Function
        
        Public Function GetInvoicePdf(ByVal request As WcfTrylogycWebsite.FacturaPdfRequest) As WcfTrylogycWebsite.FacturaPdfResponse Implements WcfTrylogycWebsite.IService.GetInvoicePdf
            Return MyBase.Channel.GetInvoicePdf(request)
        End Function
        
        Public Function GetInvoicePdfAsync(ByVal request As WcfTrylogycWebsite.FacturaPdfRequest) As System.Threading.Tasks.Task(Of WcfTrylogycWebsite.FacturaPdfResponse) Implements WcfTrylogycWebsite.IService.GetInvoicePdfAsync
            Return MyBase.Channel.GetInvoicePdfAsync(request)
        End Function
        
        Public Function Register(ByVal request As WcfTrylogycWebsite.RegisterRequest) As WcfTrylogycWebsite.RegisterResponse Implements WcfTrylogycWebsite.IService.Register
            Return MyBase.Channel.Register(request)
        End Function
        
        Public Function RegisterAsync(ByVal request As WcfTrylogycWebsite.RegisterRequest) As System.Threading.Tasks.Task(Of WcfTrylogycWebsite.RegisterResponse) Implements WcfTrylogycWebsite.IService.RegisterAsync
            Return MyBase.Channel.RegisterAsync(request)
        End Function
    End Class
End Namespace
